api_config:
  api_url: http://localhost:8000/api/v1
image_folder_configs:
- name: felinoscope_2000
  mode: tagless
  das_name: felinoscope_das
  folder_structure:
    extensions:
    - .jpg
    - .jpeg
    - .png
    - .tiff
    timezone: America/Montreal
    filename_format: null
    timestamp_source: mtime
  variables:
  - name: felinoscope_2000_turbidity_image
    parameter_name: turbidity_image
    source_unit_name: '-'
    destination_unit_name: '-'
    directory_path: test_data/images/felinoscope_2000
    equipment_name: felinoscope_2000
