api_config:
api_url: http://localhost:8000/api/v1

## enter configuration for all scada tags in the PLC here. We are using a the SCADA database impporter.

mode: tagged
das_name: pilEAUTE_SCADA
signal_interface_name: pilEAUTE_PLC
