"""QUDT SPARQL client and ParameterHasUnit INSERT generator.

Uses only stdlib — no new dependencies.
"""

from __future__ import annotations

import json
import urllib.parse
import urllib.request
from typing import Any

QUDT_SPARQL = "https://www.qudt.org/fuseki/qudt/sparql"

_SPARQL_TEMPLATE = """
PREFIX qudt: <http://qudt.org/schema/qudt/>
SELECT ?unit WHERE {{
  <{quantity_kind_iri}> qudt:applicableUnit ?unit .
}}
"""


def fetch_applicable_units(quantity_kind_iri: str, timeout: int = 10) -> list[str]:
    """Return QUDT unit IRIs applicable to quantity_kind_iri, or [] on network failure."""
    sparql = _SPARQL_TEMPLATE.format(quantity_kind_iri=quantity_kind_iri)
    params = urllib.parse.urlencode({"query": sparql, "format": "application/sparql-results+json"})
    url = f"{QUDT_SPARQL}?{params}"
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            data = json.loads(resp.read().decode())
        return [b["unit"]["value"] for b in data["results"]["bindings"]]
    except Exception as exc:
        print(f"[ontology_query] WARNING: QUDT unreachable for {quantity_kind_iri}: {exc}")
        return []


def build_parameter_has_unit_inserts(schema: dict[str, Any], platform: str = "mssql") -> str:
    """Generate INSERT INTO ParameterHasUnit rows from QUDT + manual_units.

    1. Build unit_name→id and unit_qudt_iri→id maps from Unit seed_data.
    2. For each Parameter seed_data row:
       a. ValueKind_ID == 4 (Image): skip.
       b. QUDT_QuantityKind_IRI present: query QUDT applicableUnits, intersect with known IRIs.
       c. Resolve manual_units names to IDs (fail loudly on unknown names).
       d. Union both sets (deduplicated).
    3. Emit INSERT rows for all (Parameter_ID, Unit_ID) pairs.
    Returns "" if no rows were produced.
    """
    unit_table = schema.get("Unit", {}).get("table", {})
    unit_rows: list[dict] = unit_table.get("seed_data") or []

    name_to_id: dict[str, int] = {}
    iri_to_id: dict[str, int] = {}
    for row in unit_rows:
        uid = row["Unit_ID"]
        name_to_id[row["Unit"]] = uid
        if row.get("QUDT_IRI"):
            iri_to_id[row["QUDT_IRI"]] = uid

    param_table = schema.get("Parameter", {}).get("table", {})
    param_rows: list[dict] = param_table.get("seed_data") or []

    if platform == "mssql":
        full_table = "[dbo].[ParameterHasUnit]"
    else:
        full_table = '"dbo"."ParameterHasUnit"'

    insert_lines: list[str] = [f"-- ParameterHasUnit (generated by ontology_query.py)"]

    for param in param_rows:
        pid = param["Parameter_ID"]
        value_kind = param.get("ValueKind_ID", 1)
        if value_kind == 4:
            continue

        unit_ids: set[int] = set()

        qudt_iri = param.get("QUDT_QuantityKind_IRI")
        if qudt_iri:
            applicable = fetch_applicable_units(qudt_iri)
            for unit_iri in applicable:
                if unit_iri in iri_to_id:
                    unit_ids.add(iri_to_id[unit_iri])

        for unit_name in param.get("manual_units", []):
            if unit_name not in name_to_id:
                raise ValueError(
                    f"Parameter '{param['Parameter']}' lists manual unit '{unit_name}' "
                    f"which is not in Unit seed_data. Fix Parameter.yaml."
                )
            unit_ids.add(name_to_id[unit_name])

        for uid in sorted(unit_ids):
            insert_lines.append(
                f"INSERT INTO {full_table} ([Parameter_ID], [Unit_ID]) VALUES ({pid}, {uid});"
            )

    if len(insert_lines) == 1:
        return ""

    return "\n".join(insert_lines) + "\n"
