-- ============================================================
-- Fixture seed (seed_fixtures.sql)
--
-- Contains ONLY sections that are NOT auto-generated from YAML seed_data:
--   1. Procedures (3 rows)
--   2. Watershed + HydrologicalCharacteristics + UrbanCharacteristics (1 TEST_ row each)
--   3. Laboratory (1 TEST_ row)
--
-- Unit (13 rows), Parameter (18 rows), and ParameterHasUnit rows are
-- now generated by uv run mkdocs build → sql_generation_scripts/v4.1.0_seed_mssql.sql.
--
-- All other fixed vocabulary tables (ValueKind, ChannelKind,
-- DataProvenanceKind, ProcessingKind, SignalInterfaceKind,
-- SignalInterfacePortKind, QualityCode, AnnotationKind, BinKind,
-- CampaignKind, EquipmentEventKind, ControlLoopPortKind,
-- ProcessUnitKind, SampleKind, SampleCollectionKind) are also
-- seeded by the auto-generated seed script.
--
-- No Equipment, EquipmentModel, Site, SamplingPoint, Campaign,
-- Channel, Observation, or Value rows — those are created by the
-- importer on first run.
-- ============================================================

SET NOCOUNT ON;

-- ============================================================
-- Procedures (3 standard ones)
-- ============================================================
INSERT INTO [dbo].[Procedures] ([ProcedureName], [Description], [ProcedureLocation])
VALUES (N'Grab sampling', N'Manual grab sample collected at water surface', N'/procedures/grab_sampling.pdf');

INSERT INTO [dbo].[Procedures] ([ProcedureName], [Description], [ProcedureLocation])
VALUES (N'24h composite', N'Time-weighted 24-hour composite sample via autosampler', N'/procedures/composite_24h.pdf');

INSERT INTO [dbo].[Procedures] ([ProcedureName], [Description], [ProcedureLocation])
VALUES (N'Online continuous', N'Continuous in-situ measurement with data logging', N'/procedures/online_continuous.pdf');

-- ============================================================
-- Watershed (1 row, TEST_ prefix)
-- ============================================================
INSERT INTO [dbo].[Watershed] ([Name], [Description], [SurfaceArea], [ConcentrationTime], [ImperviousSurface])
VALUES (N'TEST_Rivière Saint-Charles', N'TEST watershed — Quebec City urban catchment', 550.0, 180, 35.5);

INSERT INTO [dbo].[HydrologicalCharacteristics] ([UrbanArea], [Forest], [Wetlands], [Cropland], [Meadow], [Grassland])
VALUES (35.5, 25.0, 5.0, 10.0, 12.5, 12.0);

INSERT INTO [dbo].[LandUse] ([Commercial], [GreenSpaces], [Industrial], [Institutional], [Residential], [Agricultural], [Recreational])
VALUES (15.0, 8.0, 12.0, 5.0, 45.0, 5.0, 10.0);

-- ============================================================
-- Laboratory (Site_ID is nullable — no dummy site needed)
-- ============================================================
INSERT INTO [dbo].[Laboratory] ([Name], [Site_ID], [Description])
VALUES (N'TEST_modelEAU Water Quality Lab', NULL, N'TEST lab — in-house water quality analysis at Université Laval');

PRINT 'Fixture seed loaded: 3 procedures, 1 watershed, 1 lab.';
